services:
  postgres:
    image: postgres:16-alpine
    container_name: ins-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ins
      POSTGRES_PASSWORD: ins_dev_password
      POSTGRES_DB: ins_commerce_hub
    volumes:
      - ins-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ins -d ins_commerce_hub" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: ins-redis
    ports:
      - "6380:6379"
    volumes:
      - ins-redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

volumes:
  ins-postgres-data:
  ins-redis-data:
