/**
 * Centralized error codes — all modules import from here.
 * Never use ad-hoc error strings in controllers.
 */
export const ErrorCodes = {
    // Auth
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    FORBIDDEN: 'FORBIDDEN',

    // Validation
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',

    // Resources
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

    // Import
    REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
    INVALID_SKU_FORMAT: 'INVALID_SKU_FORMAT',
    DUPLICATE_SKU_IN_FILE: 'DUPLICATE_SKU_IN_FILE',
    SKU_EXISTS_IN_DB: 'SKU_EXISTS_IN_DB',
    INVALID_CATEGORY: 'INVALID_CATEGORY',
    INVALID_PRICE: 'INVALID_PRICE',
    ZERO_PRICE: 'ZERO_PRICE',
    INVALID_IMAGE_URL: 'INVALID_IMAGE_URL',
    INVALID_BARCODE: 'INVALID_BARCODE',
    INVALID_WEIGHT: 'INVALID_WEIGHT',
    DUPLICATE_ROW: 'DUPLICATE_ROW',
    EMPTY_FILE: 'EMPTY_FILE',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',

    // Shopify
    SHOPIFY_API_ERROR: 'SHOPIFY_API_ERROR',
    SHOPIFY_RATE_LIMITED: 'SHOPIFY_RATE_LIMITED',
    MAPPING_NOT_FOUND: 'MAPPING_NOT_FOUND',

    // Generic
    INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
